import Head from 'next/head'
import Layout from '../components/Layout'
import { Row } from 'react-bootstrap'

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Kontakt</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='../logo.svg' />
      </Head>

      <Row className='mt-3'>
        <h1>Kontak</h1>
        <p>
          Diese Webseite ist das Resultat eines Schulprojekts zur Erstellung
          einer Vermarktungseite für Bäume und Hölzer. In dieser Form dienst sie
          rein akademischen Zwecken und ist nicht kommerziell.
        </p>

        <h2>Anschrift</h2>
        <p>DHBW Mosbach</p>
        <p>Lohrtalweg 10</p>
        <p>74821 Mosbach</p>

        <h2>E-Mail</h2>
        <p>Sie können uns per Mail erreichen unter</p>
        <a href='mailto:neumannc06@gmail.com?subject=Kontakt'>E-Mail</a>
      </Row>
    </Layout>
  )
}
